/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import interfaces.IBoletoService;
import interfaces.IEventoService;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import models.Boleto;
import models.Evento;
import services.BoletoService;
import services.EventoService;



/**
 *
 * @author martinez
 */
public class frmBoletos extends javax.swing.JFrame {
    private String idUsuario;
    private IEventoService eventoService;
    private IBoletoService boletoService;
    /**
     * Creates new form frmCompra
     */
    public frmBoletos(String idUsuario) throws SQLException{
        this.idUsuario = idUsuario;
        initComponents();
        setLocationRelativeTo(null);
        this.eventoService = new EventoService();
        this.boletoService = new BoletoService();
        cargarEventos();
    }
    
    private void cargarEventos() throws SQLException {
        List<Evento> todosLosEventos = eventoService.getTodosLosEventos();
        DefaultComboBoxModel<String> model = new DefaultComboBoxModel<>();
        for(Evento e : todosLosEventos){
            model.addElement("ID: " + e.getId() + ", Evento: " + e.getNombre());
        }
        cmbEventos.setModel(model);
        cmbEventos.setEnabled(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbEventos = new javax.swing.JComboBox<>();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txfSerie = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txfFila = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txfAsiento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txfPrecio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txfControl = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        cmbEventos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar.png"))); // NOI18N

        btnAgregar.setBackground(new java.awt.Color(0, 102, 83));
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.setBorder(null);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Seleccione un evento:");

        txfSerie.setBackground(new java.awt.Color(0, 51, 102));
        txfSerie.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txfSerie.setForeground(new java.awt.Color(255, 255, 255));
        txfSerie.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfSerie.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txfSerie.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Serie:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fila:");

        txfFila.setBackground(new java.awt.Color(0, 51, 102));
        txfFila.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txfFila.setForeground(new java.awt.Color(255, 255, 255));
        txfFila.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfFila.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txfFila.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Asiento:");

        txfAsiento.setBackground(new java.awt.Color(0, 51, 102));
        txfAsiento.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txfAsiento.setForeground(new java.awt.Color(255, 255, 255));
        txfAsiento.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfAsiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txfAsiento.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio:");

        txfPrecio.setBackground(new java.awt.Color(0, 51, 102));
        txfPrecio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txfPrecio.setForeground(new java.awt.Color(255, 255, 255));
        txfPrecio.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfPrecio.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txfPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Control:");

        txfControl.setBackground(new java.awt.Color(0, 51, 102));
        txfControl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txfControl.setForeground(new java.awt.Color(255, 255, 255));
        txfControl.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfControl.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txfControl.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(340, Short.MAX_VALUE)
                        .addComponent(lblMinimizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCerrar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txfSerie)
                                    .addComponent(cmbEventos, 0, 295, Short.MAX_VALUE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel3)
                                    .addComponent(txfFila)
                                    .addComponent(jLabel4)
                                    .addComponent(txfAsiento)
                                    .addComponent(jLabel5)
                                    .addComponent(txfPrecio)
                                    .addComponent(jLabel6)
                                    .addComponent(txfControl))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCerrar)
                    .addComponent(lblMinimizar))
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbEventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfFila, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfAsiento, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfControl, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        frmMenu menu;
        try {
            menu = new frmMenu(idUsuario);
            menu.setVisible(true);
            this.dispose();
        } catch (SQLException ex) {
            Logger.getLogger(frmBoletos.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }//GEN-LAST:event_lblCerrarMouseClicked

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        try{
            String selectedItem = (String) cmbEventos.getSelectedItem();
            if (selectedItem == null || selectedItem.contains("No hay boletos disponibles")) {
                JOptionPane.showMessageDialog(this, "Por favor seleccione un boleto valido.");
                return;
            }
            else{
                // Extraer ID del boleto seleccionado del texto del ComboBox
                String[] parts = selectedItem.split(","); // Divide la cadena en partes usando la coma como delimitador
                String idPart = parts[0]; // Obten la primera parte "ID: X"
                String[] idParts = idPart.split(":"); // Divide la primera parte usando ":" como delimitador
                int eventoId = Integer.parseInt(idParts[1].trim()); // Obten el ID y elimina espacios en blanco

                String nSerie = txfSerie.getText();
                int _evento = eventoId;
                String fila = txfFila.getText();
                int asiento = Integer.parseInt(txfAsiento.getText());
                Double precioOriginal = Double.parseDouble(txfPrecio.getText());
                Double precioActual = Double.parseDouble(txfPrecio.getText());
                String nControl = txfControl.getText();
                String estado = "Disponible";
                try {
                    int affected = boletoService.añadirBoleto(nSerie, _evento, fila, asiento, precioOriginal, precioActual, nControl, estado);
                    JOptionPane.showMessageDialog(null, "Boleto agregado con ID: " + affected);
                } catch (SQLException ex) {
                    Logger.getLogger(frmBoletos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "Se produjo un error, revise todos los campos e intentelo de nuevo. " + e.getMessage(), "Presentacion:Error", JOptionPane.ERROR_MESSAGE);
        }
        LimpiarCampos();
    }//GEN-LAST:event_btnAgregarActionPerformed
    private void LimpiarCampos(){
        txfSerie.setText("");
        txfFila.setText("");
        txfAsiento.setText("");
        txfPrecio.setText("");
        txfControl.setText("");
    }
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                try {
//                    new frmBoletos().setVisible(true);
//                } catch (SQLException ex) {
//                    Logger.getLogger(frmBoletos.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JComboBox<String> cmbEventos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JTextField txfAsiento;
    private javax.swing.JTextField txfControl;
    private javax.swing.JTextField txfFila;
    private javax.swing.JTextField txfPrecio;
    private javax.swing.JTextField txfSerie;
    // End of variables declaration//GEN-END:variables
}
