/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import dao.EventoDAO;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import models.Evento;

/**
 *
 * @author martinez
 */
public class frmMenu extends javax.swing.JFrame {
    private String idUsuario;
    /**
     * Creates new form frmMenu
     */
    public frmMenu(String idUsuario) throws SQLException {
        this.idUsuario = idUsuario;
        initComponents();
        setLocationRelativeTo(null);
        cargarEventos();
    }
    
    private void cargarEventos() throws SQLException {
        pnlContenedor.setLayout(new BoxLayout(pnlContenedor, BoxLayout.Y_AXIS));
        EventoDAO eventoDAO = new EventoDAO();
        try {
            List<Evento> eventos = eventoDAO.obtenerTodosLosEventos();
            for (Evento evento : eventos) {
                
                JPanel panelEvento = new JPanel();
                panelEvento.setLayout(null);
                panelEvento.setPreferredSize(new Dimension(738, 102));
                panelEvento.setBackground(new Color(0, 61, 122));

                JLabel lblNombre = new JLabel("Nombre: " + evento.getNombre());
                lblNombre.setForeground(Color.WHITE);
                lblNombre.setBounds(10, 10, 200, 30);
                panelEvento.add(lblNombre);

                JLabel lblVenue = new JLabel("Venue: " + evento.getVenue());
                lblVenue.setForeground(Color.WHITE);
                lblVenue.setBounds(10, 40, 200, 30);
                panelEvento.add(lblVenue);

                JLabel lblFecha = new JLabel("Fecha: " + evento.getFecha());
                lblFecha.setForeground(Color.WHITE);
                lblFecha.setBounds(10, 70, 200, 30);
                panelEvento.add(lblFecha);
                
                panelEvento.addMouseListener(new MouseAdapter() {
                    @Override
                    public void mouseClicked(MouseEvent e) {
                        try {
                            frmCompra compra = new frmCompra(evento, idUsuario);
                            compra.setVisible(true);
                            dispose();
                        } catch (SQLException ex) {
                            Logger.getLogger(frmMenu.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }
                });
                
                pnlContenedor.add(panelEvento);
                pnlContenedor.add(Box.createRigidArea(new Dimension(0, 10)));
            }

            pnlContenedor.revalidate();
            pnlContenedor.repaint();
        } catch (SQLException e) {
            System.out.println("Error al cargar los eventos: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPantalla = new javax.swing.JPanel();
        btnPerfil = new javax.swing.JButton();
        btnHistorial = new javax.swing.JButton();
        lblBuscarIcono = new javax.swing.JLabel();
        txfBuscar = new javax.swing.JTextField();
        lblCerrar = new javax.swing.JLabel();
        lblMinimizar = new javax.swing.JLabel();
        btnEntrar4 = new javax.swing.JButton();
        btnEntrar5 = new javax.swing.JButton();
        spnContenedor = new javax.swing.JScrollPane();
        pnlContenedor = new javax.swing.JPanel();
        lblSeleccionMenu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlPantalla.setBackground(new java.awt.Color(0, 51, 102));

        btnPerfil.setBackground(new java.awt.Color(0, 102, 83));
        btnPerfil.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPerfil.setForeground(new java.awt.Color(255, 255, 255));
        btnPerfil.setText("Perfil");
        btnPerfil.setBorder(null);
        btnPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPerfilMouseClicked(evt);
            }
        });

        btnHistorial.setBackground(new java.awt.Color(0, 102, 83));
        btnHistorial.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHistorial.setForeground(new java.awt.Color(255, 255, 255));
        btnHistorial.setText("Historial");
        btnHistorial.setBorder(null);
        btnHistorial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        lblBuscarIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/buscar.png"))); // NOI18N

        txfBuscar.setBackground(new java.awt.Color(0, 102, 83));
        txfBuscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txfBuscar.setForeground(new java.awt.Color(255, 255, 255));
        txfBuscar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txfBuscar.setText("Buscar");
        txfBuscar.setBorder(null);

        lblCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cerrar.png"))); // NOI18N
        lblCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCerrarMouseClicked(evt);
            }
        });

        lblMinimizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minimizar.png"))); // NOI18N

        btnEntrar4.setBackground(new java.awt.Color(0, 154, 125));
        btnEntrar4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntrar4.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar4.setText("Proximos eventos");
        btnEntrar4.setBorder(null);
        btnEntrar4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btnEntrar5.setBackground(new java.awt.Color(0, 102, 83));
        btnEntrar5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEntrar5.setForeground(new java.awt.Color(255, 255, 255));
        btnEntrar5.setText("Tus boletos");
        btnEntrar5.setBorder(null);
        btnEntrar5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        spnContenedor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        spnContenedor.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        pnlContenedor.setBackground(new java.awt.Color(0, 51, 102));
        pnlContenedor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout pnlContenedorLayout = new javax.swing.GroupLayout(pnlContenedor);
        pnlContenedor.setLayout(pnlContenedorLayout);
        pnlContenedorLayout.setHorizontalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 776, Short.MAX_VALUE)
        );
        pnlContenedorLayout.setVerticalGroup(
            pnlContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        spnContenedor.setViewportView(pnlContenedor);

        lblSeleccionMenu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblSeleccionMenu.setForeground(new java.awt.Color(255, 255, 255));
        lblSeleccionMenu.setText("Proximos eventos:");

        javax.swing.GroupLayout pnlPantallaLayout = new javax.swing.GroupLayout(pnlPantalla);
        pnlPantalla.setLayout(pnlPantallaLayout);
        pnlPantallaLayout.setHorizontalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnContenedor)
                    .addGroup(pnlPantallaLayout.createSequentialGroup()
                        .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEntrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnEntrar5, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblBuscarIcono)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txfBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(lblMinimizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCerrar))
                    .addGroup(pnlPantallaLayout.createSequentialGroup()
                        .addComponent(lblSeleccionMenu)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnlPantallaLayout.setVerticalGroup(
            pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPantallaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCerrar)
                    .addComponent(lblMinimizar)
                    .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblBuscarIcono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlPantallaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnHistorial, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEntrar4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEntrar5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(txfBuscar, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(52, 52, 52)
                .addComponent(lblSeleccionMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spnContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPantalla, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPerfilMouseClicked
        // TODO add your handling code here:
        frmPerfil perfil = new frmPerfil(idUsuario);
        this.dispose();
        perfil.setVisible(true);
    }//GEN-LAST:event_btnPerfilMouseClicked

    private void lblCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCerrarMouseClicked
        // TODO add your handling code here:
        frmLogin login = new frmLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblCerrarMouseClicked

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new frmMenu().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar4;
    private javax.swing.JButton btnEntrar5;
    private javax.swing.JButton btnHistorial;
    private javax.swing.JButton btnPerfil;
    private javax.swing.JLabel lblBuscarIcono;
    private javax.swing.JLabel lblCerrar;
    private javax.swing.JLabel lblMinimizar;
    private javax.swing.JLabel lblSeleccionMenu;
    private javax.swing.JPanel pnlContenedor;
    private javax.swing.JPanel pnlPantalla;
    private javax.swing.JScrollPane spnContenedor;
    private javax.swing.JTextField txfBuscar;
    // End of variables declaration//GEN-END:variables
}
